name: zuzu
version: 1.0.0+1
publish_to: none
description: Short Video & Social Media App
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.2
  get: ^4.6.5
  get_storage: ^2.1.1
  dio: ^5.2.1+1
  google_fonts: any
  logger: ^1.3.0
  flutter_svg: ^2.0.6
  lottie: ^2.4.0
  flutter_spinkit: ^5.2.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  pinput: ^2.2.31
  video_player: ^2.6.1
  visibility_detector: ^0.4.0+2
  pull_to_refresh_flutter3: ^2.0.1
  cached_network_image: ^3.2.3
  package_info_plus: ^4.0.2
  flutter_sticky_header: ^0.6.5
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.4
#  sentry_flutter: ^7.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/logo/app_launcher.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/
    - assets/logo/
    - assets/on_boarding_images/
    - assets/icons/
    - assets/icons/Additional/
    - assets/icons/Bold/
    - assets/icons/Light-Border/
    - assets/icons/Light-Outline/
    - assets/icons/Curved/
    - assets/images/
  uses-material-design: true

